// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNRMwzYMQaxs1JL7Pgme86ysa_hXoEh30',
    appId: '1:472580519085:web:749cc7947d6b79f9428224',
    messagingSenderId: '472580519085',
    projectId: 'fy-project-28375',
    authDomain: 'fy-project-28375.firebaseapp.com',
    storageBucket: 'fy-project-28375.firebasestorage.app',
    measurementId: 'G-MVMWNBSPQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy-bdVLSvAnvgba40YVXPo79fkaLPU-o4',
    appId: '1:472580519085:android:e2e28a3a69bafe24428224',
    messagingSenderId: '472580519085',
    projectId: 'fy-project-28375',
    storageBucket: 'fy-project-28375.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFjqVgGyp0TVQlqD8yvO7sgpc2wITvaK4',
    appId: '1:472580519085:ios:7f174fb3b9381f7a428224',
    messagingSenderId: '472580519085',
    projectId: 'fy-project-28375',
    storageBucket: 'fy-project-28375.firebasestorage.app',
    iosBundleId: 'com.example.fsep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNRMwzYMQaxs1JL7Pgme86ysa_hXoEh30',
    appId: '1:472580519085:web:6b4929ff21f50b18428224',
    messagingSenderId: '472580519085',
    projectId: 'fy-project-28375',
    authDomain: 'fy-project-28375.firebaseapp.com',
    storageBucket: 'fy-project-28375.firebasestorage.app',
    measurementId: 'G-ERLV70S0BM',
  );
}
