<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::table('behavior_events', function (Blueprint $table) {
            // Unique identifier generated by the client (Flutter) to prevent
            // duplicate processing during synchronization retries.
            $table->string('client_uuid', 64)->nullable()->unique()->after('exam_session_id');
        });
    }

    public function down(): void
    {
        Schema::table('behavior_events', function (Blueprint $table) {
            $table->dropColumn('client_uuid');
        });
    }
};
